metrics:
  - name: probe_success
    source: blackbox_exporter
    description: "Probe success flag (1 = success, 0 = failure)"
    promql_template: 'probe_success{namespace="$ns", job="blackbox-tcp"}'
    unit: boolean
    value_type: gauge
    default_step: "5s"
    labels_to_keep: [namespace, service, instance, job]
    scope_label_key: "service"