"""add_fault_tolerance_and_recovery_completeness_indicators

Revision ID: c954122c824b
Revises: c2d3e4f5a6b7
Create Date: 2026-04-26 19:26:28.761646+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c954122c824b'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE isoindicator ADD VALUE IF NOT EXISTS 'FAULT_TOLERANCE_RATIO'")
    op.execute("ALTER TYPE isoindicator ADD VALUE IF NOT EXISTS 'RECOVERY_COMPLETENESS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
