"""add_subcharacteristics_and_extend_indicators

Revision ID: 748624ce3631
Revises: c954122c824b
Create Date: 2026-04-28 04:13:10.871732+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748624ce3631'
down_revision: Union[str, None] = 'c954122c824b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "CREATE TYPE isosubcharacteristics AS ENUM "
        "('FAULTLESSNESS', 'AVAILABILITY', 'FAULT_TOLERANCE', 'RECOVERABILITY')"
    )
    op.add_column(
        'evaluation_indicators',
        sa.Column(
            'sub_characteristic',
            sa.Enum('FAULTLESSNESS', 'AVAILABILITY', 'FAULT_TOLERANCE', 'RECOVERABILITY',
                    name='isosubcharacteristics', create_type=False),
            nullable=False,
        )
    )
    op.create_index(op.f('ix_evaluation_indicators_sub_characteristic'), 'evaluation_indicators', ['sub_characteristic'], unique=False)
    op.drop_constraint(op.f('experiment_evaluations_experiment_id_key'), 'experiment_evaluations', type_='unique')
    op.drop_index(op.f('ix_experiment_evaluations_experiment_id'), table_name='experiment_evaluations')
    op.create_index(op.f('ix_experiment_evaluations_experiment_id'), 'experiment_evaluations', ['experiment_id'], unique=True)

    for value in (
        'MEAN_TIME_TO_FAILURE',
        'MEAN_FAULT_NOTIFICATION_TIME',
        'RESPONSE_TIME_P95',
        'ERROR_RATE',
        'CPU_UTILIZATION',
        'MEMORY_UTILIZATION',
    ):
        op.execute(f"ALTER TYPE isoindicator ADD VALUE IF NOT EXISTS '{value}'")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_evaluations_experiment_id'), table_name='experiment_evaluations')
    op.create_index(op.f('ix_experiment_evaluations_experiment_id'), 'experiment_evaluations', ['experiment_id'], unique=False)
    op.create_unique_constraint(op.f('experiment_evaluations_experiment_id_key'), 'experiment_evaluations', ['experiment_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_evaluation_indicators_sub_characteristic'), table_name='evaluation_indicators')
    op.drop_column('evaluation_indicators', 'sub_characteristic')
    op.execute("DROP TYPE IF EXISTS isosubcharacteristics")
    # ### end Alembic commands ###
