"""create_clusters_table

Revision ID: 5c31b344e8dd
Revises: 04ab311fa94b
Create Date: 2026-02-04 07:26:07.573774+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c31b344e8dd'
down_revision: Union[str, None] = '04ab311fa94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='User-provided cluster name'),
    sa.Column('kind_name', sa.String(length=255), nullable=False, comment='The kind cluster name'),
    sa.Column('app_preset', sa.String(length=100), nullable=True, comment='The application preset used for this cluster'),
    sa.Column('status', sa.Enum('PENDING', 'PROVISIONING', 'READY', 'FAILED', 'DELETING', 'DELETED', name='clusterstatus'), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True, comment='Additional information about the current status of the cluster'),
    sa.Column('kubeconfig_path', sa.String(length=500), nullable=True),
    sa.Column('ports', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='The cluster ports configuration'),
    sa.Column('victoriametrics_url', sa.String(length=500), nullable=True, comment='The VictoriaMetrics URL for the cluster'),
    sa.Column('baseline_path', sa.String(length=500), nullable=True, comment='The path to the baseline configuration for the cluster'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='The expiration time of the cluster (default: created_at + 7 days)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='The deletion time of the cluster'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_expires_at'), 'clusters', ['expires_at'], unique=False)
    op.create_index(op.f('ix_clusters_kind_name'), 'clusters', ['kind_name'], unique=True)
    op.create_index(op.f('ix_clusters_status'), 'clusters', ['status'], unique=False)
    op.create_index(op.f('ix_clusters_tenant_id'), 'clusters', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clusters_tenant_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_status'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_kind_name'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_expires_at'), table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
