"""add_baseline_metrics_column_in_chaos_entity

Revision ID: 5f0599e8d622
Revises: 5ebab22fc33a
Create Date: 2026-05-14 04:22:22.925980+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f0599e8d622'
down_revision: Union[str, None] = '5ebab22fc33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chaos_experiments', sa.Column('baseline_metrics', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chaos_experiments', 'baseline_metrics')
    # ### end Alembic commands ###
