"""add_probe_actual_value

Revision ID: 256a803dbcd6
Revises: df0ab4a326b7
Create Date: 2026-05-05 10:00:07.874226+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '256a803dbcd6'
down_revision: Union[str, None] = 'df0ab4a326b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployments', 'probe_thresholds',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Per-deployment SLO threshold overrides for Litmus probes. Keys: success_rate_slo, p99_recovery_ratio, liveness_timeout_s, memory_restart_max, etc. Falls back to global PROBE_DEFAULT_* settings.',
               existing_comment='Per-deployment SLO threshold overrides for Litmus probes. Falls back to global PROBE_DEFAULT_* settings.',
               existing_nullable=True)
    op.add_column('probe_results', sa.Column('actual_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('probe_results', 'actual_value')
    op.alter_column('deployments', 'probe_thresholds',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Per-deployment SLO threshold overrides for Litmus probes. Falls back to global PROBE_DEFAULT_* settings.',
               existing_comment='Per-deployment SLO threshold overrides for Litmus probes. Keys: success_rate_slo, p99_recovery_ratio, liveness_timeout_s, memory_restart_max, etc. Falls back to global PROBE_DEFAULT_* settings.',
               existing_nullable=True)
    # ### end Alembic commands ###
