"""create observability tables

Revision ID: e9e14c7d2c2d
Revises: d4e5f6a7b8c9
Create Date: 2026-03-08 12:50:28.955224+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9e14c7d2c2d"
down_revision: Union[str, None] = "d4e5f6a7b8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observability_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("deployment_id", sa.UUID(), nullable=False),
        sa.Column(
            "phase",
            sa.Enum("BASELINE", "CHAOS", "RECOVERY", name="collectionphase"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "COLLECTING", "COMPLETED", "FAILED", name="sessionstatus"
            ),
            nullable=False,
        ),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("target_namespace", sa.String(length=255), nullable=False),
        sa.Column("collection_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("collection_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observability_sessions_cluster_id"),
        "observability_sessions",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_sessions_deployment_id"),
        "observability_sessions",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_sessions_status"),
        "observability_sessions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_sessions_tenant_id"),
        "observability_sessions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "metric_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("sli_name", sa.String(length=50), nullable=False),
        sa.Column("sub_characteristics", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("promql_query", sa.Text(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("slo_target", sa.Float(), nullable=False),
        sa.Column("slo_operator", sa.String(length=10), nullable=False),
        sa.Column("slo_met", sa.Boolean(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "raw_response", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["observability_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metric_snapshots_session_id"),
        "metric_snapshots",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "reliability_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("deployment_id", sa.UUID(), nullable=False),
        sa.Column("baseline_session_id", sa.UUID(), nullable=False),
        sa.Column("chaos_session_id", sa.UUID(), nullable=False),
        sa.Column("recovery_session_id", sa.UUID(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("availability_score", sa.Float(), nullable=False),
        sa.Column("faultlessness_score", sa.Float(), nullable=False),
        sa.Column("fault_tolerance_score", sa.Float(), nullable=False),
        sa.Column("recoverability_score", sa.Float(), nullable=False),
        sa.Column("details", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["baseline_session_id"], ["observability_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["chaos_session_id"], ["observability_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["recovery_session_id"], ["observability_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reliability_reports_baseline_session_id"),
        "reliability_reports",
        ["baseline_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reliability_reports_chaos_session_id"),
        "reliability_reports",
        ["chaos_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reliability_reports_cluster_id"),
        "reliability_reports",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reliability_reports_deployment_id"),
        "reliability_reports",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reliability_reports_recovery_session_id"),
        "reliability_reports",
        ["recovery_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reliability_reports_tenant_id"),
        "reliability_reports",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reliability_reports_tenant_id"), table_name="reliability_reports"
    )
    op.drop_index(
        op.f("ix_reliability_reports_recovery_session_id"),
        table_name="reliability_reports",
    )
    op.drop_index(
        op.f("ix_reliability_reports_deployment_id"), table_name="reliability_reports"
    )
    op.drop_index(
        op.f("ix_reliability_reports_cluster_id"), table_name="reliability_reports"
    )
    op.drop_index(
        op.f("ix_reliability_reports_chaos_session_id"),
        table_name="reliability_reports",
    )
    op.drop_index(
        op.f("ix_reliability_reports_baseline_session_id"),
        table_name="reliability_reports",
    )
    op.drop_table("reliability_reports")
    op.drop_index(op.f("ix_metric_snapshots_session_id"), table_name="metric_snapshots")
    op.drop_table("metric_snapshots")
    op.drop_index(
        op.f("ix_observability_sessions_tenant_id"), table_name="observability_sessions"
    )
    op.drop_index(
        op.f("ix_observability_sessions_status"), table_name="observability_sessions"
    )
    op.drop_index(
        op.f("ix_observability_sessions_deployment_id"),
        table_name="observability_sessions",
    )
    op.drop_index(
        op.f("ix_observability_sessions_cluster_id"),
        table_name="observability_sessions",
    )
    op.drop_table("observability_sessions")
    # ### end Alembic commands ###
