"""create_jobs_table

Revision ID: f86b52b41e91
Revises: 5c31b344e8dd
Create Date: 2026-02-04 07:26:28.901302+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f86b52b41e91"
down_revision: Union[str, None] = "5c31b344e8dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum(
                "PROVISION_CLUSTER",
                "RUN_PIPELINE",
                "TEARDOWN_CLUSTER",
                "COLLECT_BASELINE_METRICS",
                "CLEANUP_EXPIRED",
                name="jobtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELED",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "current_phase",
            sa.String(length=100),
            nullable=True,
            comment="Current pipeline phase",
        ),
        sa.Column(
            "celery_task_id",
            sa.String(length=255),
            nullable=True,
            comment="The Celery task ID associated with this job",
        ),
        sa.Column(
            "result",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Job result data",
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "progress_percentage",
            sa.Integer(),
            nullable=True,
            comment="Job progress percentage",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jobs_celery_task_id"), "jobs", ["celery_task_id"], unique=True
    )
    op.create_index(op.f("ix_jobs_cluster_id"), "jobs", ["cluster_id"], unique=False)
    op.create_index(op.f("ix_jobs_job_type"), "jobs", ["job_type"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_tenant_id"), "jobs", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_tenant_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_job_type"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_cluster_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_celery_task_id"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
