"""create_raw_metrics_sample_tables

Revision ID: a92167ab19dd
Revises: f7a8b9c0d1e2
Create Date: 2026-04-21 15:36:12.401910+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a92167ab19dd'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_metric_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.Enum('BASELINE', 'FAULT', 'RECOVERY', name='metricphase'), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['chaos_experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_metric_samples_experiment_phase_metric', 'raw_metric_samples', ['experiment_id', 'phase', 'metric_name'], unique=False)
    op.create_index('ix_raw_metric_samples_experiment_phase_metric_time', 'raw_metric_samples', ['experiment_id', 'phase', 'metric_name', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_metric_samples_experiment_phase_metric_time', table_name='raw_metric_samples')
    op.drop_index('ix_raw_metric_samples_experiment_phase_metric', table_name='raw_metric_samples')
    op.drop_table('raw_metric_samples')
    # ### end Alembic commands ###
